// qiankun-example-angular/src/main.ts
import './qiankun/public-path';
import { enableProdMode, NgModuleRef } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule } from './app/app.module';
import { environment } from './environments/environment';
import actions from './qiankun/qiankun-actions';

if (environment.production) {
  enableProdMode();
}

let app: void | NgModuleRef<AppModule>;
async function render(props = {}) {
  app = await platformBrowserDynamic()
    .bootstrapModule(AppModule)
    .catch((err) => console.error(err));
}

if (!(window as any).__POWERED_BY_QIANKUN__) {
  console.log('独立运行--angular');
  render();
}

export async function bootstrap(props: Object) {
  console.log(props);
}

export async function mount(props: Object) {
  actions.setActions(props);
  render(props);
}

export async function unmount(props: Object) {
  console.log(props);
  // @ts-ignore
  app.destroy();
}

// qiankun-example-react/src/index.js
import './qiankun/public-path'
import React from 'react';
import { createRoot } from 'react-dom/client';
import './index.css';
import App from './App';
// import reportWebVitals from './reportWebVitals';
import * as serviceWorker from './qiankun/serviceWorker';
import actions from './qiankun/qiankun-actions';

function render(props = {}) {
  const { container } = props;
  createRoot(container ? container.querySelector('#root') : document.querySelector('#root')).render(<App/>);
}

if (!window.__POWERED_BY_QIANKUN__) {
  console.log('独立运行--react');
  render();
}

export async function bootstrap() {
  console.log('进入微应用--react的项目');
}

export async function mount(props) {
  console.log('加载完成微应用--react的项目', props);
  actions.setActions(props);
  render(props);
}

export async function unmount(props) {
  console.log('卸载微应用--react的项目');
  const { container } = props;
  createRoot(container).unmount(container ? container.querySelector('#root') : document.querySelector('#root'));
}

// reportWebVitals();
serviceWorker.unregister();
